### ISSUE TITLE
Error occurs at 'Step 0: Data Preparation'

### ISSUE THREAD

**Issue by jiminbot20** [shunithaviv/bebopnet-code#2]
I ran _'gather_data_from_xml.py'_ than IndexError occurs at line 113. 
![image](https://user-images.githubusercontent.com/63258184/105704258-dfffb900-5f51-11eb-9a6c-87bf65947cab.png)
Could you please help me?
previous thing that I did is just clone the git and installed requirements

**Comment by shunithaviv** [comment]
Hi, 

Do you wish to train a new model or generate improvisations with the pre-trained model?
If you want to train, you should put your own training data in the folders as described in the README.
If you want to generate with the pre-trained model, skip to step 2.

Shunit

**Comment by mborn91** [comment]
Hi I'm getting the same issue when I have supplied my own training data in the folder structure as described in the README. (Essentially it looks like train_songs is empty) 

Is there something else I need to specify?? Cheers
