### ISSUE TITLE
Same issue for Step 0: data prep

### ISSUE THREAD

**Issue by mborn91** [shunithaviv/bebopnet-code#5]
Hi I'm getting the same issue as [https://github.com/shunithaviv/bebopnet-code/issues/2];  

however, I have supplied my own training data in the folder structure as described in the README. (Essentially it looks like train_songs is empty)

Is there something else I need to specify?? Cheers

**Comment by shunithaviv** [comment]
Hi!

train_songs is collected using this command: 
`glob.glob(args.xml_dir + "/train/*/*.xml")`

Make sure that the --xml_dir parameter is set correctly as an input and that the files are correctly placed in this structure. You can run this command separately to test your directory structure. If it's ok, then the output should be a list of xml file paths.

Shunit
