### ISSUE TITLE
Issues with music_generator

### ISSUE THREAD

**Issue by mborn91** [shunithaviv/bebopnet-code#6]
Hi guys

I am working to adapt some of your work with a different dataset (rather than extracting vectors from musicXMLs, I already have my vectors which I have successfully used to train the models). However, I am struggling with the evaluation of output. When I try using the music_generation.py, I get the following error when I try and load the converter_and_duration.pkl file:

AttributeError: 'bidict' object has no attribute 'isinv'

Do you have any ideas?

I was also thinking about setting up my own 'converter' objects, given my understanding is that they are vector representations of the underlying songform/ chord progression, however it would probably be easier to use your existing work since I am less familiar working with musicXML & the music21 library.

Cheers

**Comment by dianxin556** [comment]
I also meet the same problem.

**Comment by shunithaviv** [comment]
Hi,

Please verify that you are using the specific bidict version (bidict==0.14.0), I suspect this could cause this issue.

You can create your own converter, check out the code [here](https://github.com/shunithaviv/bebopnet-code/blob/9dfa800d3e24c53de5dc948b87a7db2bc2919b54/jazz_rnn/A_data_prep/gather_data_from_xml.py#L90) that creates the converter when using musicXMLs. Notice that it dynamically assigns the note durations values according to the specific corpus, so in your case you have to make sure it corresponds to your vector representations.

Shunit
